[env:lolin_c3_mini]
platform   = espressif32@6.9.0
board      = lolin_c3_mini
framework  = arduino
monitor_speed = 115200

upload_protocol = esptool
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0
    adafruit/Adafruit SHTC3 Library @ ^1.0.1